/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'Scicon\'">' + entity + '</span>' + html;
	}
	var icons = {
		'scicon-amazon': '&#xe902;',
		'scicon-amazon-a': '&#xe903;',
		'scicon-apache': '&#xe904;',
		'scicon-apache-wordmark': '&#xe905;',
		'scicon-apple-inc': '&#xe906;',
		'scicon-appstore': '&#xe907;',
		'scicon-arduino': '&#xe908;',
		'scicon-arduino-wordmark': '&#xe909;',
		'scicon-bing': '&#xe90a;',
		'scicon-bootstrap': '&#xe90b;',
		'scicon-brave': '&#xe90c;',
		'scicon-brave-text': '&#xe90d;',
		'scicon-brave-wordmark': '&#xe90e;',
		'scicon-chrome': '&#xe90f;',
		'scicon-c-lang': '&#xe910;',
		'scicon-c-lang-alt': '&#xe911;',
		'scicon-cloudflare': '&#xe912;',
		'scicon-cloudflare-wordmark': '&#xe913;',
		'scicon-codepen': '&#xe914;',
		'scicon-cpanel': '&#xe915;',
		'scicon-cpp-lang': '&#xe916;',
		'scicon-creative-cloud': '&#xe917;',
		'scicon-c-sharp': '&#xe918;',
		'scicon-css': '&#xe919;',
		'scicon-css-wordmark': '&#xe91a;',
		'scicon-discord': '&#xe91b;',
		'scicon-discord-text': '&#xe91c;',
		'scicon-discord-wordmark': '&#xe91d;',
		'scicon-docker': '&#xe91e;',
		'scicon-docker-wordmark': '&#xe91f;',
		'scicon-dreamweaver': '&#xe920;',
		'scicon-dribbble': '&#xe921;',
		'scicon-edge': '&#xe922;',
		'scicon-edge-alt': '&#xe923;',
		'scicon-edge-old': '&#xe924;',
		'scicon-esa': '&#xe925;',
		'scicon-esa-text': '&#xe926;',
		'scicon-esa-wordmark': '&#xe927;',
		'scicon-facebook': '&#xe928;',
		'scicon-facebook-f': '&#xe929;',
		'scicon-firefox': '&#xe92a;',
		'scicon-flickr': '&#xe92b;',
		'scicon-flickr-wordmark': '&#xe92c;',
		'scicon-fortran': '&#xe92d;',
		'scicon-f-sharp': '&#xe92e;',
		'scicon-github': '&#xe92f;',
		'scicon-github-text': '&#xe930;',
		'scicon-gitlab': '&#xe931;',
		'scicon-gitlab-text': '&#xe932;',
		'scicon-gitlab-wordmark': '&#xe933;',
		'scicon-gmail': '&#xe934;',
		'scicon-go-gopher': '&#xe935;',
		'scicon-go-lang': '&#xe936;',
		'scicon-google': '&#xe937;',
		'scicon-google-text': '&#xe938;',
		'scicon-guilded': '&#xe939;',
		'scicon-guilded-wordmark': '&#xe93a;',
		'scicon-html5': '&#xe93b;',
		'scicon-html5-wordmark': '&#xe93c;',
		'scicon-ibm': '&#xe93d;',
		'scicon-illustrator': '&#xe93e;',
		'scicon-incopy': '&#xe93f;',
		'scicon-indesign': '&#xe940;',
		'scicon-instagram': '&#xe941;',
		'scicon-instagram-alt': '&#xe942;',
		'scicon-java': '&#xe943;',
		'scicon-javascript': '&#xe944;',
		'scicon-javascript-text': '&#xe945;',
		'scicon-java-wordmark': '&#xe946;',
		'scicon-jquery': '&#xe947;',
		'scicon-jquery-slogan': '&#xe948;',
		'scicon-jquery-wordmark': '&#xe949;',
		'scicon-jsdelivr': '&#xe94a;',
		'scicon-jsdelivr-text': '&#xe94b;',
		'scicon-jsdelivr-wordmark': '&#xe94c;',
		'scicon-khan-academy': '&#xe94d;',
		'scicon-khan-academy-alt': '&#xe94e;',
		'scicon-khan-academy-text': '&#xe94f;',
		'scicon-khan-academy-wordmark': '&#xe950;',
		'scicon-kickstarter': '&#xe951;',
		'scicon-kickstarter-wordmark': '&#xe952;',
		'scicon-lightroom': '&#xe953;',
		'scicon-lightroom-classic': '&#xe954;',
		'scicon-linkedin': '&#xe955;',
		'scicon-linkedin-wordmark': '&#xe956;',
		'scicon-markdown': '&#xe957;',
		'scicon-markdown-alt': '&#xe958;',
		'scicon-mastodon': '&#xe959;',
		'scicon-matlab': '&#xe95a;',
		'scicon-maxcdn': '&#xe95b;',
		'scicon-medium': '&#xe95c;',
		'scicon-medium-text': '&#xe95d;',
		'scicon-medium-wordmark': '&#xe95e;',
		'scicon-mercedes': '&#xe95f;',
		'scicon-messenger': '&#xe960;',
		'scicon-messenger-alt': '&#xe961;',
		'scicon-meta': '&#xe962;',
		'scicon-meta-wordmark': '&#xe963;',
		'scicon-microsoft': '&#xe964;',
		'scicon-microsoft-text': '&#xe965;',
		'scicon-microsoft-wordmark': '&#xe966;',
		'scicon-mongodb-leaf': '&#xe967;',
		'scicon-mongodb-wordmark': '&#xe968;',
		'scicon-mozilla': '&#xe969;',
		'scicon-mysql': '&#xe96a;',
		'scicon-mysql-mark': '&#xe96b;',
		'scicon-mysql-text': '&#xe96c;',
		'scicon-nasa': '&#xe96d;',
		'scicon-nasa-worm': '&#xe96e;',
		'scicon-nature': '&#xe96f;',
		'scicon-nature-text': '&#xe970;',
		'scicon-nodejs': '&#xe971;',
		'scicon-nodejs-js': '&#xe972;',
		'scicon-nodejs-wordmark': '&#xe973;',
		'scicon-npm': '&#xe974;',
		'scicon-npm-alt': '&#xe975;',
		'scicon-npm-text': '&#xe976;',
		'scicon-nsf': '&#xe977;',
		'scicon-openai': '&#xe978;',
		'scicon-openai-text': '&#xe979;',
		'scicon-openai-wordmark': '&#xe97a;',
		'scicon-orcid': '&#xe97b;',
		'scicon-patreon': '&#xe97c;',
		'scicon-patreon-text': '&#xe97d;',
		'scicon-perl': '&#xe97e;',
		'scicon-perl-camel': '&#xe97f;',
		'scicon-photoshop': '&#xe980;',
		'scicon-php': '&#xe981;',
		'scicon-php-text': '&#xe982;',
		'scicon-pinterest': '&#xe983;',
		'scicon-pinterest-alt': '&#xe984;',
		'scicon-pinterest-text': '&#xe985;',
		'scicon-pinterest-wordmark': '&#xe986;',
		'scicon-playstore': '&#xe987;',
		'scicon-prelude': '&#xe988;',
		'scicon-premiere-pro': '&#xe989;',
		'scicon-python': '&#xe98a;',
		'scicon-quora': '&#xe98b;',
		'scicon-quora-alt': '&#xe98c;',
		'scicon-react': '&#xe98d;',
		'scicon-reddit': '&#xe98e;',
		'scicon-reddit-alt': '&#xe98f;',
		'scicon-reddit-text': '&#xe990;',
		'scicon-reddit-wordmark': '&#xe991;',
		'scicon-researchgate': '&#xe992;',
		'scicon-researchgate-alt': '&#xe993;',
		'scicon-sass': '&#xe994;',
		'scicon-scihook': '&#xe995;',
		'scicon-scihook-alt': '&#xe996;',
		'scicon-scihook-square': '&#xe997;',
		'scicon-skype': '&#xe998;',
		'scicon-slack': '&#xe999;',
		'scicon-slack-wordmark': '&#xe99a;',
		'scicon-spacex': '&#xe99b;',
		'scicon-spacex-alt': '&#xe99c;',
		'scicon-spotify': '&#xe99d;',
		'scicon-spotify-text': '&#xe99e;',
		'scicon-spotify-wordmark': '&#xe99f;',
		'scicon-sqlite': '&#xe9a0;',
		'scicon-sqlite-wordmark': '&#xe9a1;',
		'scicon-stackoverflow': '&#xe9a2;',
		'scicon-stackoverflow-text': '&#xe9a3;',
		'scicon-stackoverflow-wordmark': '&#xe9a4;',
		'scicon-steam': '&#xe9a5;',
		'scicon-stripe': '&#xe9a6;',
		'scicon-stripe-s': '&#xe9a7;',
		'scicon-swift': '&#xe9a8;',
		'scicon-telegram': '&#xe9a9;',
		'scicon-telegram-rounded': '&#xe9aa;',
		'scicon-tesla-inc': '&#xe9ab;',
		'scicon-tesla-text': '&#xe9ac;',
		'scicon-tesla-wordmark': '&#xe9ad;',
		'scicon-threads': '&#xe9ae;',
		'scicon-tiktok': '&#xe9af;',
		'scicon-tiktok-text': '&#xe9b0;',
		'scicon-topaz-labs': '&#xe9b1;',
		'scicon-topaz-labs-wordmark': '&#xe9b2;',
		'scicon-tua': '&#xe9b3;',
		'scicon-tua-wordmark': '&#xe9b4;',
		'scicon-tubitak': '&#xe9b5;',
		'scicon-tubitak-wordmark': '&#xe9b6;',
		'scicon-tumblr': '&#xe9b7;',
		'scicon-tumblr-text': '&#xe9b8;',
		'scicon-twitch': '&#xe9b9;',
		'scicon-twitter': '&#xe9ba;',
		'scicon-typescript': '&#xe9bb;',
		'scicon-typescript-rounded': '&#xe9bc;',
		'scicon-unity': '&#xe9bd;',
		'scicon-unity-wordmark': '&#xe9be;',
		'scicon-ups': '&#xe9bf;',
		'scicon-vimeo': '&#xe9c0;',
		'scicon-vimeo-text': '&#xe9c1;',
		'scicon-visual-studio': '&#xe9c2;',
		'scicon-visual-studio-code': '&#xe9c3;',
		'scicon-vsc-insiders': '&#xe9c4;',
		'scicon-vuejs': '&#xe9c5;',
		'scicon-whatsapp': '&#xe9c6;',
		'scicon-wikimedia': '&#xe9c7;',
		'scicon-wikimedia-text': '&#xe9c8;',
		'scicon-wikimedia-wordmark': '&#xe9c9;',
		'scicon-wikipedia': '&#xe9ca;',
		'scicon-x-corp': '&#xe9cb;',
		'scicon-yahoo': '&#xe9cc;',
		'scicon-yahoo-wordmark': '&#xe9cd;',
		'scicon-yandex': '&#xe9ce;',
		'scicon-yandex-ru': '&#xe9cf;',
		'scicon-yandex-ru-wordmark': '&#xe9d0;',
		'scicon-yandex-wordmark': '&#xe9d1;',
		'scicon-youtube': '&#xe9d2;',
		'scicon-youtube-play': '&#xe9d3;',
		'scicon-youtube-text': '&#xe9d4;',
		'scicon-youtube-wordmark': '&#xe9d5;',
		'scicon-zendesk': '&#xe9d6;',
		'scicon-zendesk-wordmark': '&#xe9d7;',
		'scicon-zotero': '&#xe9d8;',
		'scicon-zoterobib': '&#xe9d9;',
		'scicon-zotero-wordmark': '&#xe9da;',
		'scicon-acrobat': '&#xe9db;',
		'scicon-adobe': '&#xe9dc;',
		'scicon-adobe-animate': '&#xe9dd;',
		'scicon-adobe-fuse': '&#xe9de;',
		'scicon-adobe-wordmark': '&#xe9df;',
		'scicon-after-effects': '&#xe9e0;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/scicon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
